//
// Created by Rasintha_Rukshan on 03/01/2025.
//


#include <stdbool.h>
#include <dbcon.h>
#include <handle_tables.h>

bool add_fake_data() {

char *sql1 = "-- Insert into Institution\n"
             "INSERT OR IGNORE INTO Institution (InstitutionID, InstitutionName) VALUES\n"
             "(1, 'Harvard University'),\n"
             "(2, 'MIT'),\n"
             "(3, 'Stanford University');\n"
             "\n"
             "-- Insert into Category\n"
             "INSERT OR IGNORE INTO Category (CategoryID, Category) VALUES\n"
             "(1, 'Computer Science'),\n"
             "(2, 'Business'),\n"
             "(3, 'Arts');\n"
             "\n"
             "-- Insert into MinEducationLevel\n"
             "INSERT OR IGNORE INTO MinEducationLevel (EducationLevelID, EducationLevelName) VALUES\n"
             "(1, 'O/L'),\n"
             "(2, 'A/L'),\n"
             "(3, 'Bachelor'),\n"
             "(4, 'Master'),\n"
             "(5, 'PHD');\n"
             "\n"
             "-- Insert into Currency\n"
             "INSERT OR IGNORE INTO Currency (CurrencyID, CurrencyName) VALUES\n"
             "(1, 'USD'),\n"
             "(2, 'EUR'),\n"
             "(3, 'GBP'),\n"
             "(4, 'LKR');\n"
             "\n"
             "-- Insert into Gender\n"
             "INSERT OR IGNORE INTO Gender (GenderID, GenderType) VALUES\n"
             "(1, 'Male'),\n"
             "(2, 'Female'),\n"
             "(3, 'Any');\n"
             "\n"
             "-- Insert into Skills\n"
             "INSERT OR IGNORE INTO skills (SkillID, SkillName) VALUES\n"
             "(1, 'Python Programming'),\n"
             "(2, 'Data Analysis'),\n"
             "(3, 'Marketing');\n"
             "\n"
             "-- Insert into Passions\n"
             "INSERT OR IGNORE INTO passions (PassionID, PassionName) VALUES\n"
             "(1, 'Technology'),\n"
             "(2, 'Entrepreneurship'),\n"
             "(3, 'Design');\n"
             "\n"
             "-- Insert into Courses\n"
             "INSERT OR IGNORE INTO Courses (CourseID, CourseName, InstitutionID, CategoryID, Description, Duration, Fee, CurrencyID, MinAge, MaxAge, GenderID, MinEducationLevelID, level) VALUES\n"
             "(1, 'Intro to Python', 1, 1, 'Learn Python basics', '3 months', 500, 1, 18, 50, 1, 2, 'Beginner'),\n"
             "(2, 'Data Science Bootcamp', 2, 1, 'Comprehensive Data Science course', '6 months', 1500, 1, 20, 45, 2, 2, 'Intermediate'),\n"
             "(3, 'Business Strategy', 3, 2, 'Learn to formulate business strategies', '4 months', 1000, 2, 22, 50, 3, 2, 'Advanced');\n"
             "\n"
             "-- Insert into course_skills (associating skills with courses)\n"
             "INSERT OR IGNORE INTO course_skills (CourseID, SkillID) VALUES\n"
             "(1, 1),\n"
             "(2, 2), \n"
             "(3, 3); \n"
             "\n"
             "-- Insert into course_passions (associating passions with courses)\n"
             "INSERT OR IGNORE INTO course_passions (CourseID, PassionID) VALUES\n"
             "(1, 1),  \n"
             "(3, 2);"
             "-- Insert into Institution\n"
             "INSERT OR IGNORE INTO Institution (InstitutionID, InstitutionName) VALUES\n"
             "(1, 'Harvard University'),\n"
             "(2, 'MIT'),\n"
             "(3, 'Stanford University');\n"
             "\n"
             "\n"
             "-- Insert into Category\n"
             "INSERT OR IGNORE INTO Category (CategoryID, Category) VALUES\n"
             "(1, 'Computer Science'),\n"
             "(2, 'Business'),\n"
             "(3, 'Arts');\n"
             "\n"
             "-- Insert into MinEducationLevel\n"
             "INSERT OR IGNORE INTO MinEducationLevel (EducationLevelID, EducationLevelName) VALUES\n"
             "(1, 'O/L'),\n"
             "(2, 'A/L'),\n"
             "(3, 'Bachelor'),\n"
             "(4, 'Master'),\n"
             "(5, 'PHD');\n"
             "\n"
             "-- Insert into Currency\n"
             "INSERT OR IGNORE INTO Currency (CurrencyID, CurrencyName) VALUES\n"
             "(1, 'USD'),\n"
             "(2, 'EUR'),\n"
             "(3, 'GBP'),\n"
             "(4, 'LKR');\n"
             "\n"
             "-- Insert into Gender\n"
             "INSERT OR IGNORE INTO Gender (GenderID, GenderType) VALUES\n"
             "(1, 'Male'),\n"
             "(2, 'Female'),\n"
             "(3, 'Any');\n"
             "\n"
             "-- Insert into Skills\n"
             "INSERT OR IGNORE INTO skills (SkillID, SkillName) VALUES\n"
             "(1, 'Python Programming'),\n"
             "(2, 'Data Analysis'),\n"
             "(3, 'Marketing');\n"
             "\n"
             "-- Insert into Passions\n"
             "INSERT OR IGNORE INTO passions (PassionID, PassionName) VALUES\n"
             "(1, 'Technology'),\n"
             "(2, 'Entrepreneurship'),\n"
             "(3, 'Design');\n"
             "\n"
             "-- Insert into Courses\n"
             "INSERT OR IGNORE INTO Courses (CourseID, CourseName, InstitutionID, CategoryID, Description, Duration, Fee, CurrencyID, MinAge, MaxAge, GenderID, MinEducationLevelID, level) VALUES\n"
             "(1, 'Intro to Python', 1, 1, 'Learn Python basics', '3 months', 500, 1, 18, 50, 1, 1, 'Beginner'),\n"
             "(2, 'Data Science Bootcamp', 2, 1, 'Comprehensive Data Science course', '6 months', 1500, 1, 20, 45, 2, 2, 'Intermediate'),\n"
             "(3, 'Business Strategy', 3, 2, 'Learn to formulate business strategies', '4 months', 1000, 2, 22, 50, 3, 2, 'Advanced');\n"
             "\n"
             "-- Insert into course_skills (associating skills with courses)\n"
             "INSERT OR IGNORE INTO course_skills (CourseID, SkillID) VALUES\n"
             "(1, 1),\n"
             "(2, 2),\n"
             "(3, 3);\n"
             "\n"
             "-- Insert into course_passions (associating passions with courses)\n"
             "INSERT OR IGNORE INTO course_passions (CourseID, PassionID) VALUES\n"
             "(1, 1),\n"
             "(3, 2);\n"
             "\n"
             "-- Insert additional data into Institution\n"
             "INSERT OR IGNORE INTO Institution (InstitutionID, InstitutionName) VALUES\n"
             "(4, 'University of Cambridge'),\n"
             "(5, 'California Institute of Technology'),\n"
             "(6, 'University of Oxford'),\n"
             "(7, 'Princeton University'),\n"
             "(8, 'Yale University');\n"
             "\n"
             "-- Insert additional data into Category\n"
             "INSERT OR IGNORE INTO Category (CategoryID, Category) VALUES\n"
             "(4, 'Engineering'),\n"
             "(5, 'Medicine'),\n"
             "(6, 'Law'),\n"
             "(7, 'Social Sciences'),\n"
             "(8, 'Natural Sciences');\n"
             "\n"
             "-- Insert additional data into Skills\n"
             "INSERT OR IGNORE INTO skills (SkillID, SkillName) VALUES\n"
             "(4, 'Java Programming'),\n"
             "(5, 'Machine Learning'),\n"
             "(6, 'Financial Analysis'),\n"
             "(7, 'Public Speaking'),\n"
             "(8, 'Project Management'),\n"
             "(9, 'Web Development'),\n"
             "(10, 'Artificial Intelligence');\n"
             "\n"
             "-- Insert additional data into Passions\n"
             "INSERT OR IGNORE INTO passions (PassionID, PassionName) VALUES\n"
             "(4, 'Healthcare'),\n"
             "(5, 'Environmental Sustainability'),\n"
             "(6, 'Education'),\n"
             "(7, 'Social Justice'),\n"
             "(8, 'Creative Writing');\n"
             "\n"
             "-- Insert additional data into Courses\n"
             "INSERT OR IGNORE INTO Courses (CourseID, CourseName, InstitutionID, CategoryID, Description, Duration, Fee, CurrencyID, MinAge, MaxAge, GenderID, MinEducationLevelID, level) VALUES\n"
             "(4, 'Advanced Java Programming', 4, 1, 'Deep dive into Java programming', '4 months', 800, 1, 20, 45, 3, 2, 'Intermediate'),\n"
             "(5, 'Machine Learning Fundamentals', 5, 1, 'Introduction to Machine Learning', '5 months', 1200, 1, 22, 50, 3, 3, 'Intermediate'),\n"
             "(6, 'Financial Analysis for Managers', 6, 2, 'Learn financial analysis techniques', '3 months', 900, 2, 25, 55, 3, 3, 'Advanced'),\n"
             "(7, 'Public Speaking Mastery', 7, 3, 'Master the art of public speaking', '2 months', 300, 1, 18, 60, 3, 1, 'Beginner'),\n"
             "(8, 'Project Management Professional', 8, 2, 'Become a certified project manager', '6 months', 2000, 1, 23, 50, 3, 3, 'Advanced'),\n"
             "(9, 'Web Development Bootcamp', 1, 1, 'Full-stack web development course', '6 months', 1500, 1, 18, 40, 3, 2, 'Intermediate'),\n"
             "(10, 'AI and Ethics', 2, 7, 'Explore ethical implications of AI', '3 months', 700, 1, 20, 50, 3, 3, 'Intermediate');\n"
             "\n"
             "-- Insert additional data into course_skills (associating skills with courses)\n"
             "INSERT OR IGNORE INTO course_skills (CourseID, SkillID) VALUES\n"
             "(4, 4),\n"
             "(5, 5),\n"
             "(6, 6),\n"
             "(7, 7),\n"
             "(8, 8),\n"
             "(9, 9),\n"
             "(10, 10);\n"
             "\n"
             "-- Insert additional data into course_passions (associating passions with courses)\n"
             "INSERT OR IGNORE INTO course_passions (CourseID, PassionID) VALUES\n"
             "(4, 1),\n"
             "(5, 1),\n"
             "(6, 2),\n"
             "(7, 3),\n"
             "(8, 2),\n"
             "(9, 1),\n"
             "(10, 7);\n"
             "\n"
             "\n"
             "-- Insert additional data into Institution\n"
             "INSERT OR IGNORE INTO Institution (InstitutionID, InstitutionName) VALUES\n"
             "(9, 'University of Chicago'),\n"
             "(10, 'Columbia University'),\n"
             "(11, 'University of California, Berkeley'),\n"
             "(12, 'University of Toronto'),\n"
             "(13, 'ETH Zurich'),\n"
             "(14, 'University of Tokyo'),\n"
             "(15, 'National University of Singapore');\n"
             "\n"
             "-- Insert additional data into Category\n"
             "INSERT OR IGNORE INTO Category (CategoryID, Category) VALUES\n"
             "(9, 'Psychology'),\n"
             "(10, 'History'),\n"
             "(11, 'Philosophy'),\n"
             "(12, 'Physics'),\n"
             "(13, 'Chemistry'),\n"
             "(14, 'Biology'),\n"
             "(15, 'Economics');\n"
             "\n"
             "-- Insert additional data into Skills\n"
             "INSERT OR IGNORE INTO skills (SkillID, SkillName) VALUES\n"
             "(11, 'C++ Programming'),\n"
             "(12, 'Cloud Computing'),\n"
             "(13, 'Cybersecurity'),\n"
             "(14, 'Digital Marketing'),\n"
             "(15, 'UI/UX Design'),\n"
             "(16, 'Blockchain Development'),\n"
             "(17, 'DevOps'),\n"
             "(18, 'Quantum Computing'),\n"
             "(19, 'Bioinformatics'),\n"
             "(20, 'Game Development');\n"
             "\n"
             "-- Insert additional data into Passions\n"
             "INSERT OR IGNORE INTO passions (PassionID, PassionName) VALUES\n"
             "(9, 'Space Exploration'),\n"
             "(10, 'Artificial Life'),\n"
             "(11, 'Music'),\n"
             "(12, 'Film Making'),\n"
             "(13, 'Photography'),\n"
             "(14, 'Culinary Arts'),\n"
             "(15, 'Fashion Design');\n"
             "\n"
             "-- Insert additional data into Courses\n"
             "INSERT OR IGNORE INTO Courses (CourseID, CourseName, InstitutionID, CategoryID, Description, Duration, Fee, CurrencyID, MinAge, MaxAge, GenderID, MinEducationLevelID, level) VALUES\n"
             "(11, 'Advanced C++ Programming', 9, 1, 'Master C++ programming', '5 months', 1000, 1, 20, 45, 3, 2, 'Advanced'),\n"
             "(12, 'Cloud Computing Essentials', 10, 1, 'Learn the basics of cloud computing', '4 months', 1200, 1, 22, 50, 3, 3, 'Intermediate'),\n"
             "(13, 'Cybersecurity Fundamentals', 11, 1, 'Introduction to cybersecurity', '6 months', 1500, 1, 20, 45, 3, 2, 'Intermediate'),\n"
             "(14, 'Digital Marketing Strategies', 12, 2, 'Learn digital marketing techniques', '3 months', 800, 2, 18, 50, 3, 1, 'Beginner'),\n"
             "(15, 'UI/UX Design Principles', 13, 3, 'Master UI/UX design', '4 months', 900, 1, 20, 40, 3, 2, 'Intermediate'),\n"
             "(16, 'Blockchain Development', 14, 1, 'Learn blockchain technology', '6 months', 2000, 1, 22, 50, 3, 3, 'Advanced'),\n"
             "(17, 'DevOps Engineering', 15, 1, 'Become a DevOps engineer', '5 months', 1800, 1, 23, 45, 3, 3, 'Advanced'),\n"
             "(18, 'Quantum Computing Basics', 9, 12, 'Introduction to quantum computing', '3 months', 700, 1, 20, 50, 3, 3, 'Intermediate'),\n"
             "(19, 'Bioinformatics for Beginners', 10, 14, 'Learn bioinformatics basics', '4 months', 1000, 1, 22, 45, 3, 2, 'Beginner'),\n"
             "(20, 'Game Development with Unity', 11, 1, 'Create games using Unity', '6 months', 1500, 1, 18, 40, 3, 2, 'Intermediate');\n"
             "\n"
             "-- Insert additional data into course_skills (associating skills with courses)\n"
             "INSERT OR IGNORE INTO course_skills (CourseID, SkillID) VALUES\n"
             "(11, 11),\n"
             "(12, 12),\n"
             "(13, 13),\n"
             "(14, 14),\n"
             "(15, 15),\n"
             "(16, 16),\n"
             "(17, 17),\n"
             "(18, 18),\n"
             "(19, 19),\n"
             "(20, 20);\n"
             "\n"
             "-- Insert additional data into course_passions (associating passions with courses)\n"
             "INSERT OR IGNORE INTO course_passions (CourseID, PassionID) VALUES\n"
             "(11, 1),\n"
             "(12, 1),\n"
             "(13, 1),\n"
             "(14, 2),\n"
             "(15, 3),\n"
             "(16, 1),\n"
             "(17, 1),\n"
             "(18, 9),\n"
             "(19, 10),\n"
             "(20, 11);";
    drop_tables();
    create_tables();
    executeQuery(sql1, "Inserting data into individual table successful.");
    //executeQuery(sql2, "Inserting 100 rows into courses table successful.");


return true;
}

