//
// Created by Rasintha_Rukshan on 03/01/2025.
//


#include <stdbool.h>
#include <dbcon.h>
#include <handle_tables.h>

bool add_fake_data() {

char *sql1 = "-- Insert data into Institution table (10 records)\n"
            "INSERT OR IGNORE INTO Institution (InstitutionName) VALUES\n"
            "('Institution A'),\n"
            "('Institution B'),\n"
            "('Institution C'),\n"
            "('Institution D'),\n"
            "('Institution E'),\n"
            "('Institution F'),\n"
            "('Institution G'),\n"
            "('Institution H'),\n"
            "('Institution I'),\n"
            "('Institution J');\n"
            "\n"
            "-- Insert data into Category table (20 records)\n"
            "INSERT OR IGNORE INTO Category (Category) VALUES\n"
            "('Technology'),\n"
            "('Business'),\n"
            "('Science'),\n"
            "('Arts'),\n"
            "('Engineering'),\n"
            "('Law'),\n"
            "('Medicine'),\n"
            "('Psychology'),\n"
            "('Mathematics'),\n"
            "('Education'),\n"
            "('Design'),\n"
            "('History'),\n"
            "('Literature'),\n"
            "('Sports'),\n"
            "('Music'),\n"
            "('Sociology'),\n"
            "('Economics'),\n"
            "('Philosophy'),\n"
            "('Politics'),\n"
            "('Environmental Studies');\n"
            "\n"
            "-- Insert OR IGNORE data into Currency table (2 records)\n"
            "INSERT INTO Currency (CurrencyName) VALUES\n"
            "('LKR'),\n"
            "('USD');\n"
            "\n"
            "-- Insert data into Gender table (3 records)\n"
            "INSERT OR IGNORE INTO Gender (GenderType) VALUES\n"
            "('Male'),\n"
            "('Female'),\n"
            "('Any');\n"
            "\n"
            "-- Insert OR IGNORE data into MinEducationLevel table (5 records)\n"
            "INSERT INTO MinEducationLevel (EducationLevelName) VALUES\n"
            "('O/L'),\n"
            "('A/L'),\n"
            "('Bachelor'),\n"
            "('Master'),\n"
            "('PhD');"
            "INSERT OR IGNORE INTO Skills (SkillName) VALUES\n"
             "('Python Programming'),\n"
             "('Java Programming'),\n"
             "('C Programming'),\n"
             "('JavaScript Development'),\n"
             "('HTML & CSS'),\n"
             "('SQL Database Management'),\n"
             "('Data Analysis'),\n"
             "('Machine Learning'),\n"
             "('Deep Learning'),\n"
             "('Artificial Intelligence'),\n"
             "('Cybersecurity'),\n"
             "('Web Development'),\n"
             "('Mobile App Development'),\n"
             "('Cloud Computing'),\n"
             "('Project Management'),\n"
             "('Digital Marketing'),\n"
             "('SEO Optimization'),\n"
             "('UI/UX Design'),\n"
             "('Graphic Design'),\n"
             "('3D Modeling'),\n"
             "('Animation'),\n"
             "('Game Development'),\n"
             "('Networking'),\n"
             "('System Administration'),\n"
             "('Cloud Architecture'),\n"
             "('Financial Analysis'),\n"
             "('Accounting Principles'),\n"
             "('Blockchain Development'),\n"
             "('Cryptocurrency Trading'),\n"
             "('Business Analysis'),\n"
             "('Leadership'),\n"
             "('Team Management'),\n"
             "('Product Management'),\n"
             "('Business Strategy'),\n"
             "('Data Visualization'),\n"
             "('Statistical Analysis'),\n"
             "('Business Intelligence'),\n"
             "('Customer Support'),\n"
             "('Sales Strategies'),\n"
             "('Copywriting'),\n"
             "('Technical Writing'),\n"
             "('Legal Research'),\n"
             "('Contract Negotiation'),\n"
             "('Market Research'),\n"
             "('Public Speaking'),\n"
             "('Event Planning'),\n"
             "('Negotiation Skills'),\n"
             "('Human Resource Management'),\n"
             "('Team Collaboration'),\n"
             "('Time Management'),\n"
             "('Conflict Resolution'),\n"
             "('Presentation Skills'),\n"
             "('Data Encryption'),\n"
             "('Software Testing'),\n"
             "('Quality Assurance'),\n"
             "('API Development'),\n"
             "('DevOps'),\n"
             "('Database Administration'),\n"
             "('Network Security'),\n"
             "('Cloud Security'),\n"
             "('IT Support'),\n"
             "('Machine Learning Algorithms'),\n"
             "('Cloud Platforms (AWS, Azure)'),\n"
             "('SAP'),\n"
             "('Salesforce'),\n"
             "('Tableau'),\n"
             "('Power BI'),\n"
             "('Big Data Technologies'),\n"
             "('GIS Mapping'),\n"
             "('Social Media Marketing'),\n"
             "('E-commerce Management'),\n"
             "('Content Writing'),\n"
             "('Content Marketing'),\n"
             "('Customer Relationship Management'),\n"
             "('Leadership Coaching'),\n"
             "('Change Management'),\n"
             "('Strategic Planning'),\n"
             "('Accounting Software (QuickBooks, Xero)'),\n"
             "('Financial Modelling'),\n"
             "('Statistical Software (R, SAS)'),\n"
             "('Cloud Deployment'),\n"
             "('Web Scraping'),\n"
             "('Video Editing'),\n"
             "('Audio Editing'),\n"
             "('Search Engine Marketing (SEM)'),\n"
             "('Graphic Software (Photoshop, Illustrator)'),\n"
             "('3D Printing'),\n"
             "('Python Data Libraries (Pandas, NumPy)'),\n"
             "('SQL Querying'),\n"
             "('Linux Administration'),\n"
             "('Windows Server Administration'),\n"
             "('Networking Protocols'),\n"
             "('Hardware Troubleshooting'),\n"
             "('Cloud Infrastructure Management'),\n"
             "('Artificial Neural Networks'),\n"
             "('Data Cleaning'),\n"
             "('Natural Language Processing'),\n"
             "('Geographic Information Systems (GIS)'),\n"
             "('Event Management'),\n"
             "('Brand Strategy'),\n"
             "('Market Analysis'),\n"
             "('Foreign Languages'),\n"
             "('Emotional Intelligence'),\n"
             "('Customer Feedback Analysis'),\n"
             "('Product Design'),\n"
             "('Research Methodology'),\n"
             "('System Analysis'),\n"
             "('Data Structures and Algorithms'),\n"
             "('R Programming'),\n"
             "('Cloud Computing Services'),\n"
             "('E-commerce Website Development'),\n"
             "('Digital Branding'),\n"
             "('User Research'),\n"
             "('Customer Retention'),\n"
             "('B2B Sales'),\n"
             "('B2C Sales'),\n"
             "('Public Relations'),\n"
             "('Strategic Sourcing'),\n"
             "('Supply Chain Management'),\n"
             "('Data Integrity'),\n"
             "('Cloud Storage Management'),\n"
             "('Hardware Design'),\n"
             "('Robotics'),\n"
             "('Artificial Intelligence Ethics'),\n"
             "('User Interface Design'),\n"
             "('Digital Transformation'),\n"
             "('Business Automation'),\n"
             "('Mobile Gaming Development'),\n"
             "('Social Media Content Creation'),\n"
             "('Content Curation'),\n"
             "('Tech Support'),\n"
             "('IT Troubleshooting'),\n"
             "('Web Application Development'),\n"
             "('RPA (Robotic Process Automation)'),\n"
             "('Sales Forecasting'),\n"
             "('Product Roadmap Development'),\n"
             "('Business Process Improvement'),\n"
             "('Financial Accounting Analysis'),\n"
             "('Customer Data Analysis'),\n"
             "('Agile Methodology'),\n"
             "('Scrum Management'),\n"
             "('Risk Management'),\n"
             "('Data Governance'),\n"
             "('API Integration'),\n"
             "('API Testing'),\n"
             "('SAP Software'),\n"
             "('Mobile User Interface Design'),\n"
             "('User Experience Research'),\n"
             "('SEO Copywriting'),\n"
             "('Facebook Marketing'),\n"
             "('Instagram Marketing'),\n"
             "('YouTube Channel Management'),\n"
             "('Content Scheduling'),\n"
             "('Chatbot Development');";

char *sql2 = "-- Insert courses into the Courses table\n"
             "INSERT INTO Courses (CourseName, InstitutionID, CategoryID, Description, Duration, Fee, CurrencyID, MinAge, GenderID, MinEducationLevelID) VALUES\n"
             "('Data Science Basics', 1, 1, 'Learn the fundamentals of data science.', '3 months', 1500.0, 2, 18, 3, 3),\n"
             "('Machine Learning Advanced', 2, 1, 'Advanced techniques in machine learning.', '6 months', 3000.0, 2, 21, 3, 4),\n"
             "('Artificial Intelligence for Beginners', 3, 1, 'AI foundations for new learners.', '4 months', 2000.0, 1, 20, 3, 3),\n"
             "('Web Development Bootcamp', 4, 2, 'Full-stack web development course.', '5 months', 1200.0, 2, 18, 3, 3),\n"
             "('Mobile App Development', 5, 2, 'Learn to build iOS and Android apps.', '4 months', 1400.0, 1, 19, 3, 3),\n"
             "('Cybersecurity Fundamentals', 6, 3, 'Introduction to cybersecurity concepts.', '3 months', 1800.0, 2, 20, 3, 3),\n"
             "('Ethical Hacking', 7, 3, 'Hands-on ethical hacking training.', '6 months', 2500.0, 2, 21, 3, 4),\n"
             "('Cloud Computing Essentials', 8, 4, 'Basics of cloud platforms and services.', '3 months', 2000.0, 1, 18, 3, 3),\n"
             "('DevOps Practitioner', 9, 4, 'Deep dive into DevOps practices.', '5 months', 2800.0, 2, 21, 3, 4),\n"
             "('Project Management Professional', 10, 5, 'PMP certification preparation.', '6 months', 3000.0, 2, 23, 3, 4),\n"
             "('Digital Marketing', 1, 6, 'Master digital marketing skills.', '4 months', 1000.0, 1, 18, 3, 3),\n"
             "('SEO & Content Marketing', 2, 6, 'Improve SEO and create quality content.', '3 months', 800.0, 1, 18, 3, 3),\n"
             "('Business Analytics', 3, 7, 'Analyze and interpret business data.', '5 months', 2200.0, 2, 22, 3, 4),\n"
             "('Financial Modeling', 4, 7, 'Build financial models from scratch.', '4 months', 2000.0, 2, 21, 3, 4),\n"
             "('Graphic Design Basics', 5, 8, 'Learn graphic design tools and techniques.', '4 months', 1000.0, 1, 18, 3, 3),\n"
             "('UI/UX Design Fundamentals', 6, 8, 'Intro to user interface and experience design.', '4 months', 1500.0, 2, 18, 3, 3),\n"
             "('Photography for Beginners', 7, 8, 'Basics of digital photography.', '3 months', 800.0, 1, 18, 3, 3),\n"
             "('Video Editing with Premiere Pro', 8, 8, 'Master video editing skills.', '4 months', 1400.0, 1, 19, 3, 3),\n"
             "('Healthcare Management', 9, 9, 'Managing healthcare institutions effectively.', '6 months', 2500.0, 2, 23, 3, 4),\n"
             "('Introduction to Psychology', 10, 10, 'Learn psychological concepts and theories.', '3 months', 1200.0, 1, 18, 3, 3),\n"
             "('Robotics for Beginners', 1, 11, 'Hands-on robotics for new learners.', '4 months', 1800.0, 2, 19, 3, 3),\n"
             "('Mechanical Engineering Basics', 2, 11, 'Introduction to mechanical concepts.', '6 months', 3000.0, 2, 20, 3, 4),\n"
             "('Civil Engineering Fundamentals', 3, 11, 'Learn civil engineering concepts.', '5 months', 2800.0, 2, 20, 3, 4),\n"
             "('Electrical Engineering 101', 4, 11, 'Basics of electrical circuits and systems.', '4 months', 2000.0, 2, 20, 3, 4),\n"
             "('Software Testing & QA', 5, 4, 'Manual and automated testing.', '4 months', 1200.0, 1, 19, 3, 3),\n"
             "('Blockchain Essentials', 6, 12, 'Introduction to blockchain technology.', '3 months', 1500.0, 2, 20, 3, 3),\n"
             "('Cryptocurrency Trading', 7, 12, 'Learn trading with cryptocurrencies.', '2 months', 1200.0, 1, 21, 3, 3),\n"
             "('Game Development', 8, 13, 'Create games using popular engines.', '6 months', 2500.0, 2, 18, 3, 3),\n"
             "('Augmented Reality Development', 9, 13, 'Build AR applications.', '5 months', 3000.0, 2, 21, 3, 4),\n"
             "('AI-Powered Healthcare', 10, 9, 'AI in healthcare innovation.', '6 months', 3500.0, 2, 23, 3, 4),\n"
             "('Fitness Trainer Certification', 1, 14, 'Become a certified fitness trainer.', '4 months', 1000.0, 1, 18, 3, 3),\n"
             "('Yoga Instructor Course', 2, 14, 'Learn to teach yoga effectively.', '4 months', 800.0, 1, 18, 3, 3),\n"
             "('Personal Finance Management', 3, 15, 'Manage your finances better.', '3 months', 500.0, 1, 18, 3, 3),\n"
             "('Investing for Beginners', 4, 15, 'Introduction to investment strategies.', '3 months', 1000.0, 1, 21, 3, 3),\n"
             "('Business Start-up Guide', 5, 7, 'Steps to launching your own business.', '3 months', 1500.0, 2, 22, 3, 3),\n"
             "('Mobile Game Development', 6, 13, 'Develop games for mobile platforms.', '4 months', 2000.0, 1, 19, 3, 3),\n"
             "('Renewable Energy Basics', 7, 16, 'Intro to renewable energy systems.', '5 months', 2500.0, 2, 20, 3, 4),\n"
             "('Wind and Solar Energy Systems', 8, 16, 'Comprehensive study of wind and solar power.', '6 months', 3000.0, 2, 21, 3, 4),\n"
             "('3D Printing Essentials', 9, 11, 'Learn to use 3D printers.', '3 months', 1500.0, 1, 18, 3, 3),\n"
             "('Nanotechnology Basics', 10, 16, 'Introduction to nanotechnology.', '4 months', 3000.0, 2, 22, 3, 4),\n"
             "('Interior Design Basics', 1, 8, 'Fundamentals of interior design.', '3 months', 1000.0, 1, 18, 3, 3),\n"
             "('Culinary Arts', 2, 17, 'Learn to cook like a chef.', '4 months', 1200.0, 1, 18, 3, 3),\n"
             "('Baking Essentials', 3, 17, 'Master the art of baking.', '3 months', 1000.0, 1, 18, 3, 3),\n"
             "('Digital Art Basics', 4, 8, 'Learn to create stunning digital art.', '3 months', 1200.0, 1, 18, 3, 3),\n"
             "('Music Composition', 5, 18, 'Basics of music theory and composition.', '4 months', 1500.0, 1, 18, 3, 3),\n"
             "('Singing Techniques', 6, 18, 'Improve your singing skills.', '3 months', 1000.0, 1, 18, 3, 3),\n"
             "('Filmmaking Basics', 7, 8, 'Intro to filmmaking and production.', '6 months', 2500.0, 2, 18, 3, 3),\n"
             "('Cinematography', 8, 8, 'Learn advanced cinematography.', '5 months', 3000.0, 2, 21, 3, 4);"
             "-- Add skills for courses\n"
             "INSERT INTO course_skills (CourseID, SkillID) VALUES \n"
             "(1, 1), (1, 2), (2, 3), (2, 4), (3, 5), (4, 6), (5, 7), (6, 8), (6, 9), (7, 10);\n"
             "\n"
             "-- Add passions for courses\n"
             "INSERT INTO course_passions (CourseID, PassionID) VALUES \n"
             "(1, 1), (1, 2), (2, 3), (2, 4), (3, 5), (4, 6), (5, 7), (6, 8), (6, 9), (7, 10);";

    drop_tables();
    create_tables();
    executeQuery(sql1, "Inserting data into individual table successful.");
    executeQuery(sql2, "Inserting 100 rows into courses table successful.");


return true;
}
